on:
  workflow_dispatch:
  push:
    paths: ["tokens"]
    branches: main
jobs:
  build_tw:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Install, Build
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run build:vars
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Build Tailwind
      # - name: Deploy
      #   uses: JamesIves/github-pages-deploy-action@v4.4.1
      #   with:
      #      branch: gh-pages
      #      folder: docs
      #      target-folder: docs
